[tools]
uv = "0.10.11"
python = "3.14.3"
ruff = "0.14.5"

[tasks.install]
run = "uv pip install .[dev]"

[tasks.update]
run = "uv sync -U"

[tasks.outdated]
run = "uv pip list --outdated"

[tasks.format]
run = ["ruff format", "ruff check --fix"]

[tasks.check]
run = "uv run mypy ."
